name: Real DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show who pushed the code
        run: echo "Code pushed by ${{ github.actor }}"

      - name: Show which branch
        run: echo "Branch is ${{ github.ref }}"

      - name: Show all files in project
        run: ls -la

      - name: Check disk space on server
        run: df -h

      - name: Pipeline finished!
        run: echo "Pipeline completed successfully! 🎉"